# The URL the site will be built for
base_url = "https://createx-org.github.io/"

title = "CreateX Workshop."
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true
#highlight_theme = "idle"
highlight_theme = "ir-white"

render_emoji = false
external_links_target_blank = true # rel="noopener"
external_links_no_follow = false   # rel="nofollow"
external_links_no_referrer = false # rel="noreferrer"
smart_punctuation = false          # `...` to `…`, `"quote"` to `“curly”` etc

[extra]
logo_name = "CreateX"
logo_path = "logo.png"

# Add page titles here to exclude them from the nav section (case sensitive)
exclude_menu = []